import { IAdoptRequest } from "../types/Types";

export const mockAdoptRequests: IAdoptRequest[] = [
  {
    _id: "1",
    petName: "Bella",
    reason: "Looking for a companion",
    status: "pending",
    createdAt: "2025-03-01T12:00:00Z",
    name: "John Doe",
    livingSituation: "Apartment",
    mode: "Online",
    phone: "555-1234",
    email: "john.doe@example.com",
    address: "123 Main St, Springfield, IL",
  },
  {
    _id: "2",
    petName: "Max",
    reason: "Needs a loving home",
    status: "approved",
    createdAt: "2025-03-02T14:30:00Z",
    name: "Jane Smith",
    livingSituation: "House with a yard",
    mode: "In-person",
    phone: "555-5678",
    email: "jane.smith@example.com",
    address: "456 Elm St, Springfield, IL",
  },
  {
    _id: "3",
    petName: "Luna",
    reason: "Looking for a calm, quiet pet",
    status: "rejected",
    createdAt: "2025-03-03T16:00:00Z",
    name: "Mark Johnson",
    livingSituation: "Apartment",
    mode: "Online",
    phone: "555-8765",
    email: "mark.johnson@example.com",
    address: "789 Oak St, Springfield, IL",
  },
  {
    _id: "4",
    petName: "Rocky",
    reason: "Great family companion",
    status: "pending",
    createdAt: "2025-03-04T10:15:00Z",
    name: "Alice Brown",
    livingSituation: "House with a yard",
    mode: "In-person",
    phone: "555-4321",
    email: "alice.brown@example.com",
    address: "321 Pine St, Springfield, IL",
  },
  {
    _id: "5",
    petName: "Milo",
    reason: "I love dogs",
    status: "approved",
    createdAt: "2025-03-05T09:45:00Z",
    name: "Emily Davis",
    livingSituation: "Apartment",
    mode: "Online",
    phone: "555-9876",
    email: "emily.davis@example.com",
    address: "654 Maple St, Springfield, IL",
  },
];
